# Generated by Django 6.0 on 2025-12-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('amount_usdt', models.FloatField()),
                ('side', models.CharField(choices=[('BUY', 'COMPRA'), ('SELL', 'VENTA')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usdt_balance', models.FloatField(default=10000.0)),
                ('btc_balance', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('initial_capital', models.FloatField(default=10000.0)),
            ],
        ),
        migrations.CreateModel(
            name='SystemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_regime', models.CharField(choices=[('RANGING', 'Lateral (Rango)'), ('UNCERTAIN', 'Incierto (Volátil)'), ('TRENDING', 'Tendencia Fuerte (Peligro)')], default='UNCERTAIN', max_length=20)),
                ('active_strategy', models.CharField(choices=[('GRID_V11', 'Grid Bot (Acumulación)'), ('SHANNON_V13', 'Shannon (Protección)'), ('IDLE', 'Modo Espera (Cash/Hold)')], default='IDLE', max_length=20)),
                ('volatility_score', models.FloatField(default=0.0)),
                ('trend_score', models.FloatField(default=0.0)),
                ('last_switch', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_used', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=50)),
                ('pnl_realized', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
