# Generated by Django 3.2.25 on 2025-10-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='sma_cross', max_length=50)),
                ('param_fast', models.IntegerField(default=10)),
                ('param_slow', models.IntegerField(default=20)),
                ('is_enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(max_length=4)),
                ('symbol', models.CharField(max_length=20)),
                ('qty', models.FloatField()),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='NEW', max_length=20)),
                ('error', models.TextField(blank=True)),
            ],
        ),
    ]
