# Generated by Django 6.0 on 2025-12-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemstate',
            name='confirmation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='max_drawdown',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='peak_equity',
            field=models.FloatField(default=10000.0),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='pending_regime',
            field=models.CharField(default='NONE', max_length=20),
        ),
    ]
