# Generated by Django 6.0 on 2025-12-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_systemstate_confirmation_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemstate',
            name='last_optimization',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='param_adx_max',
            field=models.FloatField(default=25.0),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='param_atr_mult',
            field=models.FloatField(default=4.0),
        ),
    ]
