# Generated by Django 6.0 on 2025-12-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_systemstate_last_optimization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('equity', models.FloatField()),
                ('pnl_usd', models.FloatField()),
                ('pnl_percent', models.FloatField()),
                ('strategy_used', models.CharField(max_length=50)),
            ],
        ),
    ]
